---
#
# tasks file for ansible-role-instana_agent
#

- name: Add Instana Repository Key
  apt_key: url="https://packages.instana.io/Instana.gpg"

- name: Add Instana Apt Repository
  apt_repository: repo="deb [arch=amd64] https://_:{{ _instana.install_environment.INSTANA_AGENT_KEY }}@packages.instana.io/agent generic main" state=present

- name: Install Instana Agent
  apt: name="instana-agent-{{ _instana.package_type }}" state=latest
  environment: "{{ _instana.install_environment }}"

- name: Generate Instana Agent Override Configuration
  template: src="configuration.yaml.j2" dest="/opt/instana/agent/etc/instana/configuration-aaa.yaml" owner=root group=root mode=0640
  notify: Restart Instana Agent

- name: Configure Service Autostart
  service: name="instana-agent" enabled="{{ _instana.enable }}"

# vim: set ft=ansible:set noet:ts=2:ws=2:
